language: node_js
os: osx
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:ranch: master
  on:
    branch: gatsby-dev
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
  - "npm run build"
after_success:
  - "npm run deploy"