language: node_js
os: osx
node_js:
  - 7

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  target-branch: master
  on:
    branch: gatsby-dev
before_script:
  - 'npm i -g gatsby-cli'
  - 'npm i'
script:
  - 'npm run test'
  - 'npm run build'
after_success:
  - 'npm run postBuildDeploy'
