# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: false

# Setup
title:            Xieyang Liu
tagline:          'A Practical Idealist'
description:      '<br>'    # need to be fixed later
url:              http://lxieyang.github.io
baseurl:          /
timezone:         America/New_York
logo:             '/resources/images/homepagelogo.jpg'

author:
  name:           'Xieyang Liu'
  url:            http://lxieyang.github.io
resume:           '/resources/cv/resume_Xieyang Liu.pdf'

# paginate
#gems:             [jekyll-paginate]   # enable paginate in jekyll 3
#paginate:         5
#paginate_path:    "blogs/page:num/"


# Custom vars
version:          2.0.0

# code-sharing
github:
  homepage:       https://github.com/lxieyang
  repo:           https://github.com/lxieyang/lxieyang.github.io

# social media
facebook:
  homepage:       https://www.facebook.com/profile.php?id=100000519299083
linkedin:
  homepage:       https://www.linkedin.com/in/lxieyang

# javascript files
helper-js:        '/resources/js/help.js'
typed-js:         '/resources/js/typed.js'

collections:
  works:
    output: true
