# Dependencies
# markdown:         redcarpet
markdown:         kramdown
highlighter:      rouge

# Permalinks
# permalink:        pretty
# relative_permalinks: false

# Setup
title:            Xieyang (Michael) Liu
tagline:          'A Practical Idealist'
description:      '<br>'    # need to be fixed later
url:              http://lxieyang.github.io
baseurl:          /
timezone:         America/New_York
logo:             '/resources/images/homepagelogo.jpg'
avatar-small:     '/resources/images/avatars/lxieyang-avatar-yellowstone.jpg'
avatar:           '/resources/images/avatars/lxieyang-avatar.jpg'
cmu-avatar:       '/resources/images/avatars/cmu.png'
hcii-avatar:      '/resources/images/avatars/hcii-logo-big.jpg'

author:
  name:           'Xieyang Liu'
  url:            http://lxieyang.github.io
resume:           '/resources/cv/resume_Xieyang_Liu.pdf'
cv:               '/resources/cv/cv_Xieyang_Liu.pdf'


# paginate
#gems:             [jekyll-paginate]   # enable paginate in jekyll 3
#paginate:         5
#paginate_path:    "blogs/page:num/"

logos:
  github:         '/resources/images/footer/github-icon.png'
  facebook:       '/resources/images/footer/facebook-icon.png'
  instagram:      '/resources/images/footer/instagram-icon.png'
  linkedin:       '/resources/images/footer/linkedin-icon.png'

# Custom vars
version:          2.0.0

# code-sharing
github:
  homepage:       https://github.com/lxieyang
  repo:           https://github.com/lxieyang/lxieyang.github.io

# social media
facebook:         'https://www.facebook.com/profile.php?id=100000519299083'
instagram:        'https://www.instagram.com/xieyangl/'
linkedin:         'https://www.linkedin.com/in/lxieyang'

# javascript files
helper-js:        '/resources/js/help.js'
typed-js:         '/resources/js/typed.js'

# css files
font-css:         '/public/css/font.css'
main-css:         '/public/css/main.css'

# icon files
site-logo-original:     '/resources/images/sitelogo-original.jpg'
site-logo-compressed:   '/resources/images/sitelogo-compressed.jpg'

# project links & titles
project_titles:
  mobile_paper_reader:  'Paper Reader for Mobile Phones'
  crowd_ml:       'Crowdsourcing & Machine Learning'
  denso:          'Vehicle Crash Analysis Using human-in-the-loop Computer Vision & Crowdsourcing'
  hico:           'Learning to Detect Humans-Objects Interactions'
  travelife:      'TraveLife Entrepreneurship Project'
  laserguitar:    'Portable Laser Guitar'
  easydraw:       'EasyDraw: iPad-based Specialized Figure and Diagram Editing Application'

project_links:
  mobile_paper_reader:  '/projects/mobile-paper-reader.html'
  crowd_ml:       '/projects/crowd_ml.html'
  denso:          '/projects/denso.html'
  hico:           '/projects/hico.html'
  travelife:      '/projects/travelife.html'
  laserguitar:    '/projects/laserguitar.html'
  easydraw:       '/projects/easydraw.html'

publication_links:
  hico: '/publications.html#hico'

collections:
  projects:
    output: true
  experiences:
    output: true
