export default [
  {
    date: 'October 2021',
    location: 'Virtual',
    event: 'CSCW 2021',
    url: 'https://cscw.acm.org/2021/',
  },
  {
    date: 'October 2021',
    location: 'Virtual',
    event: 'UIST 2021',
    url: 'https://uist.acm.org/uist2021/',
  },
  {
    date: 'October 2021',
    location: 'Virtual',
    event: 'VL/HCC 2021',
    url: 'https://conf.researchr.org/home/vlhcc-2021',
  },
  {
    date: 'October 20, 2020',
    location: 'Minneapolis, MN, USA',
    event: 'UIST 2020',
    url: 'https://uist.acm.org/uist2020/',
  },
  {
    date: 'October 17, 2020',
    location: 'Minneapolis, MN, USA',
    event: 'CSCW 2020',
    url: 'https://cscw.acm.org/2020/',
  },
  {
    date: 'October 20, 2019',
    location: 'New Orleans, LA, US',
    event: 'UIST 2019',
    url: 'http://uist.acm.org/uist2019/',
  },
  {
    date: 'October 14, 2019',
    location: 'Memphis, TN, US',
    event: 'VL/HCC 2019',
    url: 'https://human-se.github.io/vlhcc2019/',
  },
  {
    date: 'May 27, 2019',
    location: 'Pittsburgh, PA, US',
    event: 'Bosch Research Pittsburgh Internship',
    url: 'https://www.bosch.us/our-company/bosch-in-the-usa/pittsburgh/',
  },
  // {
  //   date: 'May 14, 2019',
  //   location: 'Austin, TX, US',
  //   event: 'Personal Trip',
  //   url: 'https://www.austintexas.org/',
  // },
  {
    date: 'May 4, 2019',
    location: 'Glasgow, Scotland',
    event: 'CHI 2019',
    url: 'https://chi2019.acm.org/',
  },
  {
    date: 'April 21, 2018',
    location: 'Montréal, Canada',
    event: 'CHI 2018',
    url: 'https://chi2018.acm.org/',
  },
  {
    date: 'March 28, 2017',
    location: 'Cambridge, MA, US',
    event: 'Harvard Open House',
    url: 'https://www.harvard.edu/',
  },
  {
    date: 'March 25, 2017',
    location: 'Pittsburgh, PA, US',
    event: 'CMU HCII Open House',
    url: 'http://www.cmu.edu/',
  },
  {
    date: 'March 18, 2017',
    location: 'Blacksburg, VA, US',
    event: 'VT Open House',
    url: 'https://vt.edu/',
  },
  {
    date: 'March 15, 2017',
    location: 'San Diego, CA, US',
    event: 'UCSD Open House',
    url: 'https://ucsd.edu/',
  },
  {
    date: 'March 13, 2017',
    location: 'Seattle, WA, US',
    event: 'UW Open House',
    url: 'http://www.washington.edu/',
  },
];
